# Generated by Django 5.0.6 on 2025-05-29 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userdetails', '0002_alter_userdetails_id_useractivity_userinformation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizedDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_title', models.CharField(max_length=200)),
                ('deal_description', models.TextField()),
                ('deal_type', models.CharField(choices=[('DISCOUNT', 'Discount'), ('FLASH_SALE', 'Flash Sale'), ('BUNDLE', 'Bundle Offer'), ('CASHBACK', 'Cashback'), ('FREE_SHIPPING', 'Free Shipping'), ('SEASONAL', 'Seasonal Sale')], max_length=20)),
                ('product_category', models.CharField(max_length=100)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deal_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deal_url', models.URLField()),
                ('deal_image', models.URLField(blank=True, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_clicked', models.BooleanField(default=False)),
                ('is_purchased', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_deals', to='userdetails.userdetails')),
            ],
            options={
                'verbose_name': 'Personalized Deal',
                'verbose_name_plural': 'Personalized Deals',
                'ordering': ['-created_at'],
            },
        ),
    ]
