# Generated by Django 5.0.6 on 2026-02-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('TOS', 'Terms of Service'), ('PRIVACY', 'Privacy Policy'), ('RETURN', 'Return Policy'), ('FAQ', 'FAQ'), ('SUPPORT', 'Support'), ('CONTACT', 'Contact')], max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='policy/')),
                ('text_content', models.TextField(blank=True, help_text='Optional text content if no file is uploaded', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Policies',
            },
        ),
    ]
