# Generated by Django 5.0.6 on 2025-05-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sellerDetails',
            fields=[
                ('sellerId', models.UUIDField(primary_key=True, serialize=False)),
                ('sellerMobile', models.IntegerField()),
                ('sellerAddress', models.CharField(max_length=50)),
                ('sellerCity', models.CharField(max_length=50)),
                ('sellerState', models.CharField(max_length=50)),
                ('sellerPincode', models.IntegerField()),
                ('sellerCountry', models.CharField(max_length=50)),
                ('sellerGST', models.CharField(max_length=50)),
                ('sellerName', models.CharField(max_length=50)),
                ('sellerEmail', models.EmailField(max_length=50)),
                ('sellerPassword', models.CharField(max_length=20)),
            ],
        ),
    ]
