# Generated by Django 5.0.6 on 2025-05-29 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellerdetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('sellerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellerdetails.sellerdetails')),
            ],
        ),
    ]
